spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/davinci
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    naming:
      physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


druid:
  filters: stat
  maxActive: 20
  initialSize: 1
  maxWait: 30000
  minIdle: 10
  maxIdle: 15
  timeBetweenEvictionRunsMills: 60000
  minEvictableIdleTimeMills: 300000
  validationQuery: SELECT 1
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  maxOpenPreparedStatements: 20
  removeAbandoned: true
  removeAbandonedTimeout: 1800
  logAbandoned: true

  spring:
    mvc:
      hiddenmethod:
        filter:
          enabled: true